name: stocks-prod

networks:
  appnet:

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      discovery.type: single-node
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
      DISABLE_SECURITY_PLUGIN: "false"
      DISABLE_INSTALL_DEMO_CONFIG: "false"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "${OS_PASS}"
    volumes:
      - $OS_DATA_DIR:/usr/share/opensearch/data
      - $OS_LOG_DIR:/usr/share/opensearch/logs
    networks: [appnet]
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    #sysctls:
    #  - vm.max_map_count=262144

  backend:
    image: backend:latest
    env_file: ./.env
    expose:
      - "8000"
    networks: [appnet]

  frontend:
    image: frontend:latest   # NGINX image that proxies /api -> http://backend:8000/
    depends_on: [backend]
    networks: [appnet]
    ports:
      - "80:80"              # expose only the web entrypoint

  ingest:
    image: ingest:latest
    env_file: ./.env
    networks: [appnet]
    profiles: ["jobs"]        # keeps it out of 'up -d' by default
    restart: "no"             # batch job; don't restart
    entrypoint: [ "python" ]
